language: php

sudo: false
dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  paths:
    - vendor

before_script:
  - composer self-update
  - composer install --optimize-autoloader --no-interaction --prefer-dist

script: composer test

after_success:
- bash <(curl -s https://codecov.io/bash)

branches:
  only: master