language: php

dist: trusty

php:
  - 7.3
  - 7.4
  - 8.0

cache:
  directories:
    - $HOME/.composer/cache/files
    
before_script:
  - composer self-update
  - composer install --optimize-autoloader --no-interaction --prefer-dist

script: composer test

after_success:
- bash <(curl -s https://codecov.io/bash)

branches:
  only: master