language: php

sudo: false
dist: trusty

php:
  - 7.0
  - 7.1
  - hhvm
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    include:
        - php: 7.0
          env: deps=low
    fast_finish: true

before_script:
  - if [ "$deps" == "low" ]; then composer update --prefer-dist --prefer-lowest --prefer-stable; fi
  - if [ "$deps" != "low" ]; then composer install --prefer-dist; fi

script: composer test

after_success:
- bash <(curl -s https://codecov.io/bash)

branches:
  only: master